//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_TT.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Department
    {
        public long Index { get; set; }
        public string Name { get; set; }
        public string NameInEng { get; set; }
        public string Code { get; set; }
        public Nullable<long> ParentIndex { get; set; }
        public string CompanyID { get; set; }
        public string Description { get; set; }
        public Nullable<double> WorkingDays { get; set; }
        public Nullable<double> WorkingHours { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public string Note { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
    }
}
