//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_TT.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeSystem
    {
        public long Index { get; set; }
        public string EmployeeATID { get; set; }
        public Nullable<long> SystemIndex { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public string Helper { get; set; }
        public string ResetPasswordCode { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string Level4 { get; set; }
        public string Level5 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<short> HRPro7Portal { get; set; }
        public Nullable<short> TrainingPortal { get; set; }
        public Nullable<short> EvaluationPortal { get; set; }
        public Nullable<short> PleasureEstimatingPortal { get; set; }
        public Nullable<short> EclaimPortal { get; set; }
        public Nullable<short> RecruitmentPortal { get; set; }
        public Nullable<int> SystemGroup { get; set; }
    }
}
