//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_TT.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee
    {
        public string EmployeeATID { get; set; }
        public byte[] Image { get; set; }
        public string EmployeeCode { get; set; }
        public string CardNumber { get; set; }
        public string LastName { get; set; }
        public string MidName { get; set; }
        public string FirstName { get; set; }
        public string NickName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> JoinedDate { get; set; }
        public Nullable<short> DayOfBirth { get; set; }
        public Nullable<short> MonthOfBirth { get; set; }
        public Nullable<short> YearOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<int> Ethnic { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> HouseHold { get; set; }
        public string NativeCity { get; set; }
        public string NRIC { get; set; }
        public Nullable<System.DateTime> DateOfNRIC { get; set; }
        public string PlaceOfNRIC { get; set; }
        public Nullable<int> EmployeeKind { get; set; }
        public Nullable<int> EducationIndex { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<short> MaritalSatus { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> MarkForDelete { get; set; }
        public Nullable<System.DateTime> MaritalDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
        public Nullable<System.DateTime> UnionJoinedDate { get; set; }
        public Nullable<int> NativeCityIndex { get; set; }
        public string NativeCity_District { get; set; }
        public string SocialInsNo { get; set; }
        public string NativeCity_Wards { get; set; }
    }
}
