//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_TT.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_WorkingInfo
    {
        public long Index { get; set; }
        public string EmployeeATID { get; set; }
        public Nullable<long> DepartmentIndex { get; set; }
        public Nullable<long> PositionIndex { get; set; }
        public Nullable<long> TitlesIndex { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<long> ManagedDepartment { get; set; }
        public string DirectManager { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<bool> CreateSeparatedSalary { get; set; }
        public string ManagedOtherDepartments { get; set; }
        public string Note { get; set; }
        public Nullable<int> EmployeeKind { get; set; }
        public Nullable<short> Synched { get; set; }
        public string JobDescription { get; set; }
    }
}
