//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_TT.DatabaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR_Department> HR_Department { get; set; }
        public virtual DbSet<HR_Employee> HR_Employee { get; set; }
        public virtual DbSet<HR_EmployeeSystem> HR_EmployeeSystem { get; set; }
        public virtual DbSet<HR_WorkingInfo> HR_WorkingInfo { get; set; }
        public virtual DbSet<MS_ValidLocationList> MS_ValidLocationList { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TA_EmployeeSpecialShiftDetail> TA_EmployeeSpecialShiftDetail { get; set; }
        public virtual DbSet<TA_TimeLog> TA_TimeLog { get; set; }
    }
}
