//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_TT.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_TimeLog
    {
        public string EmployeeATID { get; set; }
        public System.DateTime Time { get; set; }
        public string MachineSerial { get; set; }
        public Nullable<short> InOutMode { get; set; }
        public Nullable<short> SpecifiedMode { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<long> EventIndex { get; set; }
        public Nullable<bool> Suggest { get; set; }
    }
}
